######################################################################
# Automatically generated by qmake (2.01a) Sun Sep 6 20:44:29 2009
######################################################################

TEMPLATE = app
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += \
	main.cpp \
	schedule.cpp \

HEADERS += \
	schedule.h \ 
