######################################################################
# Automatically generated by qmake (2.01a) Sun Sep 6 20:44:29 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
